#! python

count = 7 

while count == 7:
    varie = raw_input("Enter name or quit")

    if varie == "Aidan" or varie == "Aidan Paine-Heise":
     print "you suck try again."
    elif varie == "quit":
      print "goodbye"
      count = 1
    else:
      print varie + " your better than aidan"
